[pytest]
minversion = 6.0
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:starlette.testclient
    ignore::DeprecationWarning:httpx
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --strict-markers
    --tb=short